name: deploy

on: [push, pull_request]
#  push:
#    tags:
#      - "v*.*.*"
#
#  workflow_dispatch:
#    inputs:
#      test_triton:
#        description: 'Manually test triton'
#        required: false
#        type: boolean
#        default: false

jobs:
  test_functions:
    if: startsWith(github.ref, 'refs/tags/') == true
    runs-on: [self-hosted, linux-a100]
    timeout-minutes: 4320 # 72hours
    environment: 'prod'
    container:
      image: nvcr.io/nvidia/tritonserver:22.12-py3
      options: "--gpus=all --ipc=host --user root -e PIP_CACHE_DIR=/root/.cache/pip"
      volumes:
        - /nvme/github-actions/pip-cache:/root/.cache/pip
    steps:
      - name: Setup systems
        run: |
          rm /etc/apt/sources.list.d/cuda*.list
          apt-get update && apt-get install -y --no-install-recommends rapidjson-dev libgoogle-glog-dev libgl1
          rm -rf /var/lib/apt/lists/*
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install pytorch
        run: |
          echo $(pwd)
          python3 -m pip cache dir
          python3 -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
          python3 -m pip install cmake packaging
      - name: Install lmdeploy from pypi
        if: startsWith(github.ref, 'refs/tags/') == true
        run: |
          python3 -m pip install lmdeploy[all]
          python3 -m pip install -r requirements/test.txt
          lmdeploy check_env
      - name: Install lmdeploy from source
        if: startsWith(github.ref, 'refs/tags/') != true
        run: |
          python3 -m pip install -r requirements.txt -r requirements/test.txt
          cp -r /__w/build ./build
          cd build
          bash ../generate.sh
          make -j$(nproc) && make install
          cd ..
          python3 -m pip install .
          lmdeploy check_env
      - name: Test lmdeploy
        run: |
          echo "TODO"
      - name: Clear workfile
        if: always()
        run: |
          export repo_root=$(pwd)
          echo $repo_root
          chmod -R 777 $repo_root
          rm -rf $repo_root/*

  test_triton_a100:
    # if: inputs.test_triton == true || startsWith(github.ref, 'refs/tags/') == true
    runs-on: [self-hosted, linux-a100]
    timeout-minutes: 4320 # 72hours
    environment: 'prod'
    env:
      HF_MODEL: /nvme/qa_test_models/internlm-chat-20b
      WORKSPACE: /nvme/qa_test_models/triton_workspace/internlm-chat-20b-w4
      TB_MODEL: /nvme/qa_test_models/autotest_model/internlm-chat-20b-w4-turbomind
    steps:
      - uses: actions/checkout@v2
      - name: Generate Quantization Parameter
        run: |
          docker run --rm --gpus='"device=6,7"' \
            -v ${HF_MODEL}:/root/workspace/model \
            -v ${WORKSPACE}:/root/workspace/workdir \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_ADMIN \
            --security-opt seccomp=unconfined \
            --env NCCL_LAUNCH_MODE=GROUP \
            openmmlab/lmdeploy:latest \
            lmdeploy lite calibrate \
            --model /root/workspace/model \
            --calib_dataset 'c4' \
            --calib_samples 128 \
            --calib_seqlen 2048 \
            --work_dir /root/workspace/workdir
      - name: Quantize Weights
        run: |
          docker run --rm --gpus='"device=6,7"' \
            -v ${HF_MODEL}:/root/workspace/model \
            -v ${WORKSPACE}:/root/workspace/workdir \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_ADMIN \
            --security-opt seccomp=unconfined \
            --env NCCL_LAUNCH_MODE=GROUP \
            openmmlab/lmdeploy:latest \
            lmdeploy lite auto_awq \
            --model /root/workspace/model \
            --w_bits 4 \
            --w_group_size 128 \
            --work_dir /root/workspace/workdir
      - name: Convert to turbomind model
        run: |
          export ROOT_DIR=$(dirname "${TB_MODEL}")
          export BASE_NAME=$(basename "${TB_MODEL}")
          mkdir -p ${ROOT_DIR}
          docker run --rm --gpus='"device=6,7"' \
            -v ${WORKSPACE}:/root/workspace/model \
            -v ${ROOT_DIR}:/root/workspace/workdir \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_ADMIN \
            --security-opt seccomp=unconfined \
            --env NCCL_LAUNCH_MODE=GROUP \
            openmmlab/lmdeploy:latest \
            lmdeploy convert \
            --model-name internlm-20b \
            --model-path /root/workspace/model \
            --model-format awq \
            --tp 2 \
            --group-size 128 \
            --dst-path /root/workspace/workdir/${BASE_NAME}
      - name: Run triton server test
        run: |
          docker run --rm -v ${TB_MODEL}:/opt/tmpdir openmmlab/lmdeploy:latest chmod -R 777 /opt/tmpdir
          python3 -m pip install docker
          python3 .github/scripts/test_triton.py ${TB_MODEL}
      - name: Clear workfile
        if: always()
        run: |
          export repo_root=$(pwd)
          echo $repo_root
          chmod -R 777 $repo_root
          rm -rf $repo_root/*

  test_triton_3090:
    if: inputs.test_triton == true || startsWith(github.ref, 'refs/tags/') == true
    runs-on: [self-hosted, linux-3090]
    timeout-minutes: 4320 # 72hours
    environment: 'prod'
    env:
      HF_MODEL: /data1/lmdeploy-data/internlm-chat-7b-v1_1
      TB_MODEL: /data1/lmdeploy-data/workspace/internlm-chat-7b-v1_1-turbomind
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Convert to turbomind model
        run: |
          export ROOT_DIR=$(dirname "${TB_MODEL}")
          export BASE_NAME=$(basename "${TB_MODEL}")
          mkdir -p ${ROOT_DIR}
          docker run --rm --gpus=all \
            -v ${HF_MODEL}:/root/workspace/model \
            -v ${ROOT_DIR}:/root/workspace/workdir \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_ADMIN \
            --security-opt seccomp=unconfined \
            --env NCCL_LAUNCH_MODE=GROUP \
            openmmlab/lmdeploy:latest \
            lmdeploy convert \
            --model-name internlm-chat-7b \
            --model-path /root/workspace/model \
            --dst-path /root/workspace/workdir/${BASE_NAME}
      - name: Run triton server test
        run: |
          docker run --rm -v ${TB_MODEL}:/opt/tmpdir openmmlab/lmdeploy:latest chmod -R 777 /opt/tmpdir
          python3 -m pip install docker
          python3 .github/scripts/test_triton.py ${TB_MODEL}
      - name: Clear workfile
        if: always()
        run: |
          export repo_root=$(pwd)
          echo $repo_root
          chmod -R 777 $repo_root
          rm -rf $repo_root/*
