name: deploy

on: [push, pull_request]

jobs:
  test_triton:
    runs-on: [self-hosted, linux-a100]
    timeout-minutes: 4320 # 72hours
    environment: 'prod'
    env:
      HF_MODEL: /nvme/shared_data/InternLM/internlm-chat-20b-w4
      WORKSPACE: /mnt/models-new/ningsheng/workdir
      TB_MODEL: /mnt/models-new/ningsheng/internlm-chat-20b-w4-turbomind
      TP: 1
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          docker run --rm --gpus=all \
            -v ${HF_MODEL}:/root/TB_MODEL/model \
            -v $(dirname "${TB_MODEL}"):/root/workspace/workdir \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_ADMIN \
            --security-opt seccomp=unconfined \
            --env NCCL_LAUNCH_MODE=GROUP \
            openmmlab/lmdeploy:debug-ci \
            lmdeploy convert \
            --model-name internlm-20b \
            --model-path /root/workspace/model \
            --model-format awq \
            --tp ${TP} \
            --group-size 128 \
            --dst-path /root/workspace/workdir/$(basename "${TB_MODEL}")
      - name: Run triton server
        run: |
          python3 .github/scripts/test_triton.py ${TB_MODEL}
