name: publish-docker

on:

 push:
   paths-ignore:
     - "!.github/workflows/docker.yml"
     - ".github/**"
     - "docs/**"
     - "builder/**"
     - "resources/**"
     - "benchmark/**"
     - "tests/**"
     - "**/*.md"
   branches:
     - main
   tags:
     - "v*.*.*"

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    environment: 'prod'
    env:
      TAG_PREFIX: "openmmlab/lmdeploy"
    steps:
      - name: Get docker info
        run: |
          docker info
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get lmdeploy commit id
        run: |
          export commit_id=$(git log --format="%H" -n 1)
          echo "commit id = $commit_id"
          echo "COMMIT_ID=$commit_id" >> $GITHUB_ENV
      - name: Get lmdeploy version
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          echo "TAG=$TAG_PREFIX:latest"  >> $GITHUB_ENV
      - name: Get lmdeploy tag
        if: startsWith(github.ref, 'refs/tags/') == true
        run: |
          export LMDEPLOY_VERSION=$(python3 -c "import sys; sys.path.append('lmdeploy');from version import __version__;print(__version__)")
          echo $LMDEPLOY_VERSION
          echo "TAG=${TAG_PREFIX}:v${LMDEPLOY_VERSION}" >> $GITHUB_ENV
      - name: Show tag
        run: |
          echo "TAG = $TAG"
          echo "COMMIT_ID = $COMMIT_ID"
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.TAG }}
          file: ./docker/Dockerfile
          build-args: |
            COMMIT_ID=${{ env.COMMIT_ID }}
